MVCWebApplication/Models/ErrorViewModel.cs
using System;

namespace MVCWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCWebApplication/Models/NewsModel.cs
using System.Collections.Generic;

namespace MVCWebApplication.Models
{
    public class NewsModel
    {
        public News News { get; set; }
        public List<News> AllNews { get; set; }
    }

    public class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ReadTime { get; set; }
        public string Image { get; set; }
    }
}

MVCWebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCWebApplication/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCWebApplication.Interfaces;
using MVCWebApplication.Models;

namespace MVCWebApplication.Controllers
{
    public class NewsController : Controller
    {
        private readonly ILogger<NewsController> _logger;
        private readonly INews _news;

        public NewsController(ILogger<NewsController> logger, INews news)
        {
            _logger = logger;
            _news = news;
        }

        public IActionResult Index()
        {
            var model = _news.GetAllNews();
            return View(new NewsModel { AllNews = model });
        }

        public IActionResult Details(int id)
        {
            var model = _news.GetNewsById(id);
            return View("Details", new NewsModel { News = model });
        }
    }
}

MVCWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCWebApplication/Views/News/Details.cshtml
@model NewsModel

<div class="container">
    <h1>@Model.News.Title</h1>
    <p class="top-spacing">@Model.News.ReadTime</p>
    <div class="container">
        <img src="@Model.News.Image" width="300" height="300" alt="@Model.News.Title" />
        <p class="top-spacing">@Model.News.Description</p>
    </div>
    <a class="nav-link text-dark fa fa-arrow-left" asp-area="" asp-controller="News" asp-action="Index"> Back</a>
</div>

MVCWebApplication/Views/News/Index.cshtml
@model NewsModel

<div class="col-md-12">
    @foreach (var news in Model.AllNews)
    {
        <div class="col-md-4 col-sm-6">
            <a href="@Url.Action( "Details", "News", new { id = news.Id } )">
                <img src="@news.Image" width="300" height="300" alt="@news.Title" />
            </a>
            <p class="top-spacing">@news.ReadTime</p>
            <a href="@Url.Action( "Details", "News", new { id = news.Id } )">
                <p class="news-title">@news.Title</p>
            </a>
            <p>@news.Description</p>
            <a href="@Url.Action( "Details", "News", new { id = news.Id } )">
                <span class="readmore fa fa-arrow-right"> READ OUR INSIGHTS</span> <!--If this link was related to Sitecore then we could use Dictionary Item here-->
            </a>
        </div>
    }
</div>

MVCWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Triggerfish Coding Challenge</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="News" asp-action="Index">Triggerfish Coding Challenge</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Triggerfish Coding Challenge
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>